/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defencesystem2;

/**
 *
 * @author nihindugayashan
 */
public class Helicopter extends javax.swing.JFrame implements Observer{
    private boolean chaPositionValue;

    /**
     * Creates new form Helicopter
     */
    public Helicopter() {
        initComponents();
        setVisible(true);
    }
    
    @Override
    public void setAreaClear(int areavalue){
        if(areavalue > 40){
            lblAreaClear.setText("Area Is Clear.");
        }else{
            lblAreaClear.setText("Area is Not Clear.");
        }
    } 
    
    @Override
    public void setMassage(String msg){
        jTextArea.setText(msg);
    }
    
    @Override
    public void setBtnEnable(int btnvalue) {
        if(btnvalue > 80 && this.chaPositionValue == true){
            btnLaser.setEnabled(true);
        }else if(btnvalue > 60 && this.chaPositionValue == true){
            btnMissile.setEnabled(true);
            btnLaser.setEnabled(false);
        }else if(btnvalue > 40 && this.chaPositionValue == true){
            btnShoot.setEnabled(true);
            btnMissile.setEnabled(false);
            btnLaser.setEnabled(false);
        }else{
            btnShoot.setEnabled(false);
            btnMissile.setEnabled(false);
            btnLaser.setEnabled(false);
        }
    }
    
    @Override
    public void setQuickAreaClear(boolean chavalue){
        if(chavalue == true){
            lblAreaClear.setText("Area Is Clear.");
        }else{
            lblAreaClear.setText("Area is Not Clear.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jSlider1 = new javax.swing.JSlider();
        jSpinner2 = new javax.swing.JSpinner();
        lblAreaClear = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLaser = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnShoot = new javax.swing.JButton();
        btnMissile = new javax.swing.JButton();
        chaPosition = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton4.setText("Send");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 233, -1, -1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 0, 45, -1));

        jSlider1.setMajorTickSpacing(20);
        jSlider1.setMinorTickSpacing(10);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(0);
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 18, -1, 238));
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 29, 45, -1));

        lblAreaClear.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lblAreaClear.setText("Area Not Cleared");
        getContentPane().add(lblAreaClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 19, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel2.setText("Soldier Count");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 3, 77, -1));

        btnLaser.setText("Laser Operation");
        btnLaser.setEnabled(false);
        btnLaser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaserActionPerformed(evt);
            }
        });
        getContentPane().add(btnLaser, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 77, 109, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel3.setText("Ammo Count");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 32, 77, -1));

        btnShoot.setText("Shoot");
        btnShoot.setEnabled(false);
        btnShoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShootActionPerformed(evt);
            }
        });
        getContentPane().add(btnShoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 42, 109, -1));

        btnMissile.setText("Missile Operation");
        btnMissile.setEnabled(false);
        getContentPane().add(btnMissile, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 42, 109, -1));

        chaPosition.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        chaPosition.setText("Position");
        chaPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chaPositionActionPerformed(evt);
            }
        });
        getContentPane().add(chaPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 78, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 230, 285, 26));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jLabel4.setText("HELICOPTER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTextArea.setEditable(false);
        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane2.setViewportView(jTextArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 350, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnLaserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaserActionPerformed

    private void btnShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShootActionPerformed

    private void chaPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chaPositionActionPerformed
        this.chaPositionValue = chaPosition.isSelected();
    }//GEN-LAST:event_chaPositionActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaser;
    private javax.swing.JButton btnMissile;
    private javax.swing.JButton btnShoot;
    private javax.swing.JCheckBox chaPosition;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAreaClear;
    // End of variables declaration//GEN-END:variables

    
}
