/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package defencesystem2;


public class Submarine extends javax.swing.JFrame implements Observer{
    private boolean chaPositionValue;


    public Submarine() {
        initComponents();
        setVisible(true);
    }
    
    @Override
    public void setAreaClear(int areavalue){
        if(areavalue > 40){
            lblAreaClear.setText("Area Is Clear.");
        }else{
            lblAreaClear.setText("Area is Not Clear.");
        }
    }
    
    @Override
    public void setMassage(String msg){
        jTextAreaSub.setText(msg);
    }
    
    @Override
    public void setBtnEnable(int btnvalue) {
        if(btnvalue > 90 && this.chaPositionValue == true){
            btnTrident.setEnabled(true);
        }else if(btnvalue > 80 && this.chaPositionValue == true){
            btnTomahawk.setEnabled(true);
            btnTrident.setEnabled(false);
        }else if(btnvalue > 60 && this.chaPositionValue == true){
            btnSonar.setEnabled(true);
            btnTomahawk.setEnabled(false);
            btnTrident.setEnabled(false);
        }else if(btnvalue > 40 && this.chaPositionValue == true){
            btnShoot.setEnabled(true);
            btnSonar.setEnabled(false);
            btnTomahawk.setEnabled(false);
            btnTrident.setEnabled(false);
        }else{
            btnShoot.setEnabled(false);
            btnSonar.setEnabled(false);
            btnTomahawk.setEnabled(false);
            btnTrident.setEnabled(false);
        }
    }
    
    @Override
    public void setQuickAreaClear(boolean chavalue){
        if(chavalue == true){
            lblAreaClear.setText("Area Is Clear.");
        }else{
            lblAreaClear.setText("Area is Not Clear.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAreaClear = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSonar = new javax.swing.JButton();
        btnTomahawk = new javax.swing.JButton();
        chaPosition = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        btnShoot = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnTrident = new javax.swing.JButton();
        jSlider2 = new javax.swing.JSlider();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jSpinner2 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSub = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAreaClear.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lblAreaClear.setText("Area Not Cleared");
        getContentPane().add(lblAreaClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 25, -1, -1));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel2.setText("Soldier Count");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 30, 65, -1));

        btnSonar.setText("Sonar Operation");
        btnSonar.setEnabled(false);
        getContentPane().add(btnSonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 54, 100, -1));

        btnTomahawk.setText("Tomahawk Missile");
        btnTomahawk.setEnabled(false);
        btnTomahawk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomahawkActionPerformed(evt);
            }
        });
        getContentPane().add(btnTomahawk, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 83, 107, -1));

        chaPosition.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        chaPosition.setText("Position");
        chaPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chaPositionActionPerformed(evt);
            }
        });
        getContentPane().add(chaPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 97, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel3.setText("Ammo Count");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 65, 79, -1));

        btnShoot.setText("Shoot");
        btnShoot.setEnabled(false);
        btnShoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShootActionPerformed(evt);
            }
        });
        getContentPane().add(btnShoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 54, 107, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 259, 288, 21));

        btnTrident.setText("Trident-2 Missile");
        btnTrident.setEnabled(false);
        btnTrident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTridentActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrident, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 83, 100, -1));

        jSlider2.setMajorTickSpacing(20);
        jSlider2.setMinorTickSpacing(10);
        jSlider2.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.setValue(0);
        getContentPane().add(jSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 42, -1, 218));

        jButton4.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton4.setText("Send");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 259, -1, 21));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel4.setText("Energy");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 19, -1, -1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 27, 45, -1));

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jLabel5.setText("Oxigen");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 19, -1, -1));

        jSlider1.setMajorTickSpacing(20);
        jSlider1.setMinorTickSpacing(10);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setValue(0);
        getContentPane().add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 42, -1, 218));
        getContentPane().add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 62, 45, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jLabel6.setText("SUBMARINE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 0, -1, -1));

        jTextAreaSub.setEditable(false);
        jTextAreaSub.setColumns(20);
        jTextAreaSub.setRows(5);
        jScrollPane2.setViewportView(jTextAreaSub);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 370, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTomahawkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomahawkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTomahawkActionPerformed

    private void chaPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chaPositionActionPerformed
        this.chaPositionValue = chaPosition.isSelected();
    }//GEN-LAST:event_chaPositionActionPerformed

    private void btnShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShootActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShootActionPerformed

    private void btnTridentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTridentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTridentActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Submarine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Submarine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShoot;
    private javax.swing.JButton btnSonar;
    private javax.swing.JButton btnTomahawk;
    private javax.swing.JButton btnTrident;
    private javax.swing.JCheckBox chaPosition;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextAreaSub;
    private javax.swing.JLabel lblAreaClear;
    // End of variables declaration//GEN-END:variables

   
}
